export const  EarthQuake_Action={
    NEW:"NEW",
    SUCCESS:"SUCCESS",
    POSTEARTHQUAKE:"POSTEARTHQUAKE",
  CREATE:"CREATE",
    GETSPECIFIC:"GETSPECIFIC",
    NOTAUTHORIZED:"AUTHORIZED FAILED",
  
}
export const  EarthQuake_Status={
    NEW:"NEW",
    SUCCESS:"SUCCESS",
    CREATE:"CREATE",
    //POSTEARTHQUAKE:"POSTEARTHQUAKE",
    DETAILSUCCESS:"DETAILSUCCESS",
    FAILED:"FAILED"
}